Modifkfé
Orange-OpenSource/La-Va11ydette pull request #32
Opened 2022-03-17 08:37 UTC by Aniort

modif question va11ydete suite étude des tests axe

2022-03-17 09:21 UTC, SimonF30 requested changes
Oublie pas de mofidier le fichier config-checklist.json quand tu changes la checklist (nouveau critere), upgrade de la version.

2022-03-17 09:21 UTC, SimonF30 commented on json/criteres-wcag-ease-fr.json
> +		"ID": "testID-068",
attention tu t'es trompé d'ID

2022-03-17 09:21 UTC, SimonF30 commented on json/criteres-wcag-ease-en.json
> +	},{
normal que tu rajoutes ce critère que pour la version anglaise?

2022-03-17 09:22 UTC, SimonF30 commented on json/criteres-wcag-ease-fr.json
> +		"ID": "testID-068",
pareil pour la version anglaise d'ailleurs

2022-03-17 10:25 UTC, Aniort commented on json/criteres-wcag-ease-en.json
> +	},{
je corrige

2022-03-17 10:29 UTC, Aniort commented on json/criteres-wcag-ease-fr.json
> +		"ID": "testID-068",
je corrige

2022-03-18 13:46 UTC, SimonF30 reviewed
Juste une pétouille,

et j'ai un peu du mal à saisir la différence entre 

Chaque champ de formulaire possède-t-il une étiquette? et Chaque champ de formulaire a-t-il un nom accessible ?

2022-03-18 13:46 UTC, SimonF30 commented on json/criteres-wcag-ease-issues-en.json
> +			"solut8ion" : "Ensure a minimum contrast of 4.5: 1 between an un-underlined link and the surrounding text of normal sizes (less than 24px CSS and 19px CSS in bold). Ensure a minimum 3: 1 contrast
aie aie aie

2022-03-18 14:14 UTC, Aniort commented on json/criteres-wcag-ease-issues-en.json
> +			"solut8ion" : "Ensure a minimum contrast of 4.5: 1 between an un-underlined link and the surrounding text of normal sizes (less than 24px CSS and 19px CSS in bold). Ensure a minimum 3: 1 contrast
fait !

2022-03-18 14:17 UTC, Aniort commented on json/criteres-wcag-ease-issues-en.json
> +			"solut8ion" : "Ensure a minimum contrast of 4.5: 1 between an un-underlined link and the surrounding text of normal sizes (less than 24px CSS and 19px CSS in bold). Ensure a minimum 3: 1 contrast
pour ce qui est de l'étiquette, c'est juste un texte proche d"un champ, le nom accessible, c'est le fait que l'étiquette soit liée au champ (for/i"d, aria-label, title...)

2022-03-18 14:27 UTC, SimonF30 submitted a review, later dismissed

2022-03-18 14:29 UTC, PigeardSylvain requested changes
J'ai quelques corrections avant de merger (en cours de relecture)

2022-03-18 15:08 UTC, PigeardSylvain commented
Relu, c'est bon pour moi

2022-03-18 16:12 UTC, merged